In [ ]:
DATA TYPES IN PYTHON
int =  2
list = [1,2,3,"python","c"]
tuple = (1,2,3,4,5)
float = 45.56
dict = {'name':'john','lastname':'clay','rollno':56}
str = 'Pthon'   "Python"    ''' Python'''
set = {1,2,3,4,5}
bool = True,  False

In [ ]:
MUTABLE AND IMMUTABLE DATATYPES

MUTABLE:
    list
    dict
    set
IMMUTABLE:
    int
    float
    str
    tuple

In [ ]:
itrable and non iterable dataypes

iterable:
    list
    tuple
    dict
    set
    str
non iterable data types 
    int
    float

In [ ]:
_first_name = 
First_n6ame26 =

In [ ]:
Operators in Python :
    Arithmetic Operator
    + , - ,* ,/ ,// ,% ,**
    Assignment Operator 
    = , += ,-=, *=, /= ,%= ,**=
    Comparision Operators
    == ,!= ,<= ,>= ,= ,< , >
    Logical Operator
    and or not
    Identity Operator
    is is not
    Membership Operator
    in not in
    Bitwise Operator
    &, | ,^ , ~ ,<< , >>

In [1]:
roll = 20
sum = roll + 10
print(sum)

30

In [12]:
roll = 20
roll **=10
print(roll)

10240000000000

In [8]:
l = [10,20,30,40]
p = [10,20,30,40]
print(l is p)

False

In [10]:
sum1 = 20
sum2 = 20

print(sum1 is not sum2)

False

In [ ]:
Conditional Statements
    if 
    elif
    else

In [15]:
num1 = 5.5
num2 = 5

if num1 > num2 :
    print("num1 is greater than num2")
elif num2 > num1:
    print("num2 is greater than num1")
else:
    print("Both are same")

num1 is greater than num2

In [ ]:
PEP 8

In [ ]:
looping statements:
    for 
    while

In [22]:
sample_string = "I love python"

for avenger in sample_string:
    print(avenger + " a lot")

I a lot
  a lot
l a lot
o a lot
v a lot
e a lot
  a lot
p a lot
y a lot
t a lot
h a lot
o a lot
n a lot

In [23]:
l = [1,2,3,4,5,6,7,8,10......200]
for value in l:
    print(value * 3)

3
6
9
12
15
18
21
24
30

In [28]:
for value in range(1,201):
    print(value * 3)

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
54
57
60
63
66
69
72
75
78
81
84
87
90
93
96
99
102
105
108
111
114
117
120
123
126
129
132
135
138
141
144
147
150
153
156
159
162
165
168
171
174
177
180
183
186
189
192
195
198
201
204
207
210
213
216
219
222
225
228
231
234
237
240
243
246
249
252
255
258
261
264
267
270
273
276
279
282
285
288
291
294
297
300
303
306
309
312
315
318
321
324
327
330
333
336
339
342
345
348
351
354
357
360
363
366
369
372
375
378
381
384
387
390
393
396
399
402
405
408
411
414
417
420
423
426
429
432
435
438
441
444
447
450
453
456
459
462
465
468
471
474
477
480
483
486
489
492
495
498
501
504
507
510
513
516
519
522
525
528
531
534
537
540
543
546
549
552
555
558
561
564
567
570
573
576
579
582
585
588
591
594
597
600

In [ ]:
100 ... 200

In [35]:
for value in range(100,201,20):
    print(value)

100
120
140
160
180
200

In [ ]:
pass
break
continue

In [44]:
l = [10,20,30,40,-50,60,70,-80]

for value in l:
    if value < 0:
        print("Number is Negative", value)
        
        print("abc")
    else:
        print(value)

10
20
30
40
Number is Negative -50

In [ ]:
if 100:
    print("Hi")
else:
    pass

In [57]:
sample_string = "Python is programming language"

vowel_count = 0
consonent_count = 0

for value in sample_string:
    if value in "aeiouAEIOU":
        vowel_count +=1
    elif value == " ":
        continue
        
    else:
        consonent_count +=1
print(vowel_count, consonent_count)

9 18

In [61]:
l = [10,20,30,50,60]
print(l[2])

30

In [62]:
nums = [10,20,30,4,50,60]
for index,value in enumerate(nums):
    print(index,value)

0 10
1 20
2 30
3 4
4 50
5 60

In [64]:
for value1 in range(1,6):
    for value2 in range(100,201):
        print(value1 * value2)

100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
200
202
204
206
208
210
212
214
216
218
220
222
224
226
228
230
232
234
236
238
240
242
244
246
248
250
252
254
256
258
260
262
264
266
268
270
272
274
276
278
280
282
284
286
288
290
292
294
296
298
300
302
304
306
308
310
312
314
316
318
320
322
324
326
328
330
332
334
336
338
340
342
344
346
348
350
352
354
356
358
360
362
364
366
368
370
372
374
376
378
380
382
384
386
388
390
392
394
396
398
400
300
303
306
309
312
315
318
321
324
327
330
333
336
339
342
345
348
351
354
357
360
363
366
369
372
375
378
381
384
387
390
393
396
399
402
405
408
411
414
417
420
423
426
429
432
435
438
441
444
447
450
453
456
459
462
465
468
471
474
477
480
483
486
489
492
495
498
501
504
507
510
513
516
519
522
525
528
531
534
537
540
543
546
549
552
555
558
561
564
567
570
573
576
579
582
585
588
591
594
597
600
400
404
408
412
416
420
424
428
432
436
440
444
448
452
456
460
464
468
472
476
480
484
488
492
496
500
504
508
512
516
520
524
528
532
536
540
544
548
552
556
560
564
568
572
576
580
584
588
592
596
600
604
608
612
616
620
624
628
632
636
640
644
648
652
656
660
664
668
672
676
680
684
688
692
696
700
704
708
712
716
720
724
728
732
736
740
744
748
752
756
760
764
768
772
776
780
784
788
792
796
800
500
505
510
515
520
525
530
535
540
545
550
555
560
565
570
575
580
585
590
595
600
605
610
615
620
625
630
635
640
645
650
655
660
665
670
675
680
685
690
695
700
705
710
715
720
725
730
735
740
745
750
755
760
765
770
775
780
785
790
795
800
805
810
815
820
825
830
835
840
845
850
855
860
865
870
875
880
885
890
895
900
905
910
915
920
925
930
935
940
945
950
955
960
965
970
975
980
985
990
995
1000

In [ ]:
while loop:

while [condition]  => True or False
    statement
    statement

In [ ]:
num1 = 5

5 * 4 * 3 * 2 * 1 =

In [71]:
num1 = 5
result = 1
while num1 > 1:
    result = result * num1  
    num1 -=1
print(result)

120

In [ ]:
while [condition]:
    statement

In [ ]:
while 100:
    print ("infinite")